maximum:
  name: 50
  email: 255
minimum:
  password: 6
remember:
  true: 1
per_page:
  word: 5
per_lesson: 20
relationships: ["following", "followers"]
values:
  - "all"
  - "learned"
  - "not_learned"
